version: '3'
services:
  douban-docker:
    build: .
    container_name: douban-docker
    volumes:
      - assets:/app/static
    depends_on:
      - mongo
    ports:
      - 8000:3000
    networks:
      - shared-network

  mongo:
    image: mongo:4.4.29
    container_name: mongo
    restart: "always"
    volumes:
      # Persist mongodb data
      - database:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  assets:
    driver: local
    name: assets
  database:
    driver: local
    name: mongodb_data
networks:
  shared-network: